CREATE TABLE public."DeckImport" (
	"Id" int4 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START 1 CACHE 1 NO CYCLE) NOT NULL,
	"Key" uuid NOT NULL,
	"UserId" int4 NOT NULL,
	"CreatedAt" timestamptz NOT NULL,
	"UpdatedAt" timestamptz NOT NULL,
	CONSTRAINT "PK_DeckImport" PRIMARY KEY ("Id"),
	CONSTRAINT "UN_DeckImportKey" UNIQUE ("Key"),
	CONSTRAINT "FK_DeckImport_User_Id" FOREIGN KEY ("UserId") REFERENCES public."User"("Id")
);

CREATE TABLE public."DeckImportStatus" (
	"Id" int4 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START 1 CACHE 1 NO CYCLE) NOT NULL,
    "DeckImportId" int4 NOT NULL,
    "Type" int4 NOT NULL,
    "Current" boolean NOT NULL,
    "CreatedAt" timestamptz NOT NULL,
	"UpdatedAt" timestamptz NOT NULL,
    CONSTRAINT "PK_DeckImportStatus" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_DeckImportStatus_DeckImport_Id" FOREIGN KEY ("DeckImportId") REFERENCES public."DeckImport"("Id")
);

CREATE TABLE public."CardImport" (
	"Id" int4 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START 1 CACHE 1 NO CYCLE) NOT NULL,
    "Key" uuid NOT NULL,
    "DeckImportId" int4 NOT NULL,
    "Data" json NOT NULL,
    CONSTRAINT "PK_CardImport" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_CardImport_DeckImport_Id" FOREIGN KEY ("DeckImportId") REFERENCES public."DeckImport"("Id")
);

CREATE TABLE public."CardImportStatus" (
	"Id" int4 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START 1 CACHE 1 NO CYCLE) NOT NULL,
    "CardImportId" int4 NOT NULL,
    "Type" int4 NOT NULL,
    "Current" boolean NOT NULL,
    "CreatedAt" timestamptz NOT NULL,
	"UpdatedAt" timestamptz NOT NULL,
    CONSTRAINT "PK_CardImportStatus" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_CardImportStatus_CardImport_Id" FOREIGN KEY ("CardImportId") REFERENCES public."CardImport"("Id")
);
