CREATE TABLE public."User" (
	"Id" int4 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START 1 CACHE 1 NO CYCLE) NOT NULL,
	"Key" uuid NOT NULL,
	"Name" varchar(100) NOT NULL,
	"Email" varchar(100) NULL,
	"Role" int4 NOT NULL,
	"Password" varchar(128) NOT NULL,
	"CreatedAt" timestamptz NOT NULL,
	"UpdatedAt" timestamptz NOT NULL,
	"Active" BOOLEAN DEFAULT true NOT NULL,
	CONSTRAINT "PK_User" PRIMARY KEY ("Id"),
	CONSTRAINT "UN_UserKey" UNIQUE ("Key")
);

CREATE TABLE public."Deck" (
	"Id" int4 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START 1 CACHE 1 NO CYCLE) NOT NULL,
	"UserId" int4 NOT NULL,
	"Key" uuid NOT NULL,
	"Name" varchar(100) NOT NULL,
	"CommanderId" int4 NOT NULL,
	"CreatedAt" timestamptz NOT NULL,
	"UpdatedAt" timestamptz NOT NULL,
	CONSTRAINT "PK_Deck" PRIMARY KEY ("Id"),
	CONSTRAINT "UN_DeckKey" UNIQUE ("Key"),
	CONSTRAINT "FK_Deck_User_Id" FOREIGN KEY ("UserId") REFERENCES public."User"("Id")
);

CREATE TABLE public."Card" (
	"Id" int4 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START 1 CACHE 1 NO CYCLE) NOT NULL,
	"Key" uuid NOT NULL,
	"MultiverseId" int4 NOT NULL,
	"Cmc" real NOT NULL,
	"Name" varchar(150) NOT NULL,
	"Type" varchar NOT NULL,
	"ManaCost" varchar(10) NOT NULL,
	"Set" varchar(10) NOT NULL,
	"Text" varchar NOT NULL,
	"Artist" varchar(100) NOT NULL,
	"Number" varchar(10) NOT NULL,
	"Power" varchar(10) NOT NULL,
	"Toughness" varchar(10) NOT NULL,
	"Layout" varchar(20) NOT NULL,
	"ImageUrl" varchar NOT NULL,
	"ExternalId" varchar NOT NULL,
	"Rarity" int4 NOT NULL,
	"Colors" varchar[] NOT NULL,
	"Subtypes" varchar[] NOT NULL,
	"Supertypes" int4[] NOT NULL,
	"Types" int4[] NOT NULL,
	"CreatedAt" timestamptz NOT NULL,
	"UpdatedAt" timestamptz NOT NULL,
	CONSTRAINT "PK_Card" PRIMARY KEY ("Id"),
	CONSTRAINT "UN_CardKey" UNIQUE ("Key")
);

CREATE TABLE public."Ruling" (
	"Id" int4 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START 1 CACHE 1 NO CYCLE) NOT NULL,
	"CardId" int4 NOT NULL,
	"Key" uuid NOT NULL,
	"Text" varchar NOT NULL,
	"Date" timestamptz NOT NULL,
	CONSTRAINT "PK_Ruling" PRIMARY KEY ("Id"),
	CONSTRAINT "UN_RulingKey" UNIQUE ("Key"),
	CONSTRAINT "FK_Ruling_Card_Id" FOREIGN KEY ("CardId") REFERENCES public."Card"("Id")
);

CREATE TABLE public."DeckCard" (
	"Id" int4 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START 1 CACHE 1 NO CYCLE) NOT NULL,
	"Key" uuid NOT NULL,
	"Name" varchar(100) NOT NULL,
	"CardId" int4 NOT NULL,
    "DeckId" int4 NOT NULL,
    "UserId" int4 NOT NULL,
	"CreatedAt" timestamptz NOT NULL,
	"UpdatedAt" timestamptz NOT NULL,
	CONSTRAINT "PK_DeckCard" PRIMARY KEY ("Id"),
	CONSTRAINT "UN_DeckCardKey" UNIQUE ("Key"),
    CONSTRAINT "FK_DeckCard_Deck_Id" FOREIGN KEY ("DeckId") REFERENCES public."Deck"("Id"),
    CONSTRAINT "FK_DeckCard_Card_Id" FOREIGN KEY ("CardId") REFERENCES public."Card"("Id"),
    CONSTRAINT "FK_DeckCard_User_Id" FOREIGN KEY ("UserId") REFERENCES public."User"("Id")
);

CREATE TABLE public."DeckImport" (
	"Id" int4 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START 1 CACHE 1 NO CYCLE) NOT NULL,
	"Key" uuid NOT NULL,
	"UserId" int4 NOT NULL,
	"CreatedAt" timestamptz NOT NULL,
	"UpdatedAt" timestamptz NOT NULL,
	CONSTRAINT "PK_DeckImport" PRIMARY KEY ("Id"),
	CONSTRAINT "UN_DeckImportKey" UNIQUE ("Key"),
	CONSTRAINT "FK_DeckImport_User_Id" FOREIGN KEY ("UserId") REFERENCES public."User"("Id")
);

CREATE TABLE public."DeckImportStatus" (
	"Id" int4 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START 1 CACHE 1 NO CYCLE) NOT NULL,
    "DeckImportId" int4 NOT NULL,
    "Type" int4 NOT NULL,
    "Current" boolean NOT NULL,
    "CreatedAt" timestamptz NOT NULL,
	"UpdatedAt" timestamptz NOT NULL,
    CONSTRAINT "PK_DeckImportStatus" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_DeckImportStatus_DeckImport_Id" FOREIGN KEY ("DeckImportId") REFERENCES public."DeckImport"("Id")
);

CREATE TABLE public."CardImport" (
	"Id" int4 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START 1 CACHE 1 NO CYCLE) NOT NULL,
    "Key" uuid NOT NULL,
    "DeckImportId" int4 NOT NULL,
    "Data" json NOT NULL,
    CONSTRAINT "PK_CardImport" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_CardImport_DeckImport_Id" FOREIGN KEY ("DeckImportId") REFERENCES public."DeckImport"("Id")
);

CREATE TABLE public."CardImportStatus" (
	"Id" int4 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START 1 CACHE 1 NO CYCLE) NOT NULL,
    "CardImportId" int4 NOT NULL,
    "Type" int4 NOT NULL,
    "Current" boolean NOT NULL,
    "CreatedAt" timestamptz NOT NULL,
	"UpdatedAt" timestamptz NOT NULL,
    CONSTRAINT "PK_CardImportStatus" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_CardImportStatus_CardImport_Id" FOREIGN KEY ("CardImportId") REFERENCES public."CardImport"("Id")
);
